### ISSUE TITLE
10. Путь

### ISSUE THREAD

**Issue by AAKholod** [CTEI1AH/SBZalesky_Uipath_SecHash#10]
А зачем делаешь конкатенацию, если тебе нужно получить путь. Смысл от Path.Combine тогда?

![image](https://github.com/user-attachments/assets/adcfa1cc-aa3d-4cc4-95f3-71bc6f93786d)

**Comment by CTEI1AH** [comment]
ОпечатОчка

**Comment by CTEI1AH** [comment]
<img width="213" alt="{DC058548-E1FD-48EC-8AB4-B5F8908260F0}" src="https://github.com/user-attachments/assets/bcf2f347-1a8b-40f4-89c4-78c1c2fff6a7">
