### ISSUE TITLE
11. Бессмысленно 

### ISSUE THREAD

**Issue by AAKholod** [CTEI1AH/SBZalesky_Uipath_SecHash#11]
Ну на одну активность это бред скрипт делать, можно было оставить шагом в Process (пофиг что у индуса ахах)

![image](https://github.com/user-attachments/assets/ad5feee3-681d-47b0-b32e-bdbe67de12fa)

**Comment by CTEI1AH** [comment]
Я так и делал когда свой с нуля делал
Он же у меня навернулся и я его проект скачал и фиксил под себя XD

Мне объединить или пофиг сейчас уже?)

Как ты видела, я в целом в один процесс все могу объединить и без очередей всяких XD
Это не проблема XD

**Comment by AAKholod** [comment]
ахах не надо всё в одно, нужен баланс
тут оставим замечанием на будущее, обращаю внимание так сказать
