### ISSUE TITLE
12. Селекторы 3

### ISSUE THREAD

**Issue by AAKholod** [CTEI1AH/SBZalesky_Uipath_SecHash#12]
А если браузер будет другой,, робот ляжет

![image](https://github.com/user-attachments/assets/f5164b20-a90e-4184-907e-5da558740c18)

**Comment by CTEI1AH** [comment]
Скорее всего за индусом не убрался
а это где, если помнишь?
Не в закомментченом сегменте? 
У меня просто даже хрома нет, как он у меня не навернулся загадка
Или он в эдже хром откроет?

**Comment by AAKholod** [comment]
не удачно скриншнот сделала, сорян 

![image](https://github.com/user-attachments/assets/23065bca-8158-4679-9239-79b4db1067fc)
