### ISSUE TITLE
13. Универсальность

### ISSUE THREAD

**Issue by AAKholod** [CTEI1AH/SBZalesky_Uipath_SecHash#13]
Если что-то пойдёт не по плану, то робот будет вынужден закрыть всё там, где остановился и вкладка может быть другой, будет повторная ошибка.

![image](https://github.com/user-attachments/assets/0beca2dc-6fa4-4e23-aca5-dfc5f38a969e)

**Comment by CTEI1AH** [comment]
ага надо было "ACME System 1*" писать, не увидел
