### ISSUE TITLE
14. Закрытие процессов

### ISSUE THREAD

**Issue by AAKholod** [CTEI1AH/SBZalesky_Uipath_SecHash#14]
Проверила у себя, у меня меньше 5 секунд занимает вырубить приложение, даже двух браузеров. Так что не согласна, резона вырубки через консоль нет смысла. Исправлять не надо. Можно просто разобраться, что у себя может тормозить и в следующих проектах использовать активность

**Comment by CTEI1AH** [comment]
Сейчас оно почему то нормально стало работать
<img width="262" alt="{B21EC61F-80DB-4F75-AF7A-4474DFA7954B}" src="https://github.com/user-attachments/assets/1dcf0313-b439-4a81-a611-272599dcd7cd">
