### ISSUE TITLE
2. Структура проекта

### ISSUE THREAD

**Issue by AAKholod** [CTEI1AH/SBZalesky_Uipath_SecHash#2]
Наименование скриптов принимаю, но их следует разнести в соответствующие папки

![image](https://github.com/user-attachments/assets/e792dbfa-3ebb-4fc5-bbda-848e38fbb19f)

**Comment by CTEI1AH** [comment]
Ок, если я их просто в проводнике раскидаю по папкам внутри проекта, они же не потеряются?

**Comment by AAKholod** [comment]
не потеряются, но внутри вызываемые скрипты не будут выполнены, так как у них поменялся путь расположения, это нужно учитывать

**Comment by AAKholod** [comment]
из-за кучи версий проектов могла не найти актуальную версию, чтобы проверить исправления

**Comment by AAKholod** [comment]
ееее
