### ISSUE TITLE
3. Зачем это

### ISSUE THREAD

**Issue by AAKholod** [CTEI1AH/SBZalesky_Uipath_SecHash#3]
Тестовые кейсы должны быть убраны в итоговой версии. И что там за файлы?

![image](https://github.com/user-attachments/assets/a089e4e2-cf8b-40a2-bbaf-204051181648)

**Comment by AAKholod** [comment]
не правильно указала, вот это зачем

![image](https://github.com/user-attachments/assets/ed3f55c2-f86e-426a-bea5-6a0419b81a61)

**Comment by CTEI1AH** [comment]
Оно при создании уже было, я просто ничего не трогал

**Comment by AAKholod** [comment]
а, точно, это же framework
