### ISSUE TITLE
4. Cred

### ISSUE THREAD

**Issue by AAKholod** [CTEI1AH/SBZalesky_Uipath_SecHash#4]
И как он получает у тебя креды? 
![image](https://github.com/user-attachments/assets/b5d461db-bb48-49ce-a38e-3905a1bc2ccf)

**Comment by CTEI1AH** [comment]
У меня в проекте все норм, возможно у тебя не подвязалось из облака, что логично
<img width="263" alt="Без имени" src="https://github.com/user-attachments/assets/81e81c61-fc3a-4259-82ce-174ea825c9a7">
<img width="786" alt="{4EF95F28-BF38-4A24-9618-BF8374F94820}" src="https://github.com/user-attachments/assets/a52c866a-f2a3-44e2-8f4a-1cb8277ed8ad">

**Comment by AAKholod** [comment]
неа, у меня остаётся, ты же должен передать название, по которому у тебя лежат в облаке данные

**Comment by CTEI1AH** [comment]
ааа типо | in_Config("ACME_Login_Cred").ToString | передавать из конфига?

**Comment by AAKholod** [comment]
да, получается ты берёшь название данных, как они называются в облаке оркестратора

**Comment by CTEI1AH** [comment]
Да, чет оно само подвязалось из облака, я и не заметил что там не аргумент
