### ISSUE TITLE
5. Развернуть окно

### ISSUE THREAD

**Issue by AAKholod** [CTEI1AH/SBZalesky_Uipath_SecHash#5]
Бери на вооружение, все окна с которыми будет работать робот лучше разворачивать на полный экран по умолчанию. Исключение, наверное, консоль, но окна браузера точно всегда

![image](https://github.com/user-attachments/assets/32fd4014-e96e-4237-aea7-2e5c95f70197)

**Comment by CTEI1AH** [comment]
ок, а это для робота лучше или для себя для наглядности?

**Comment by AAKholod** [comment]
для всего, чтобы скриншоты с ошибками были более информативными, а также для стабильности работы, так как могут быть случае, когда нужно будет взаимодействие не по строгому пути (селектор или xpath), а по координатам, к примеру.

**Comment by CTEI1AH** [comment]
+ 
<img width="206" alt="{055CD570-B769-4970-9237-1B8FBBFAD6B0}" src="https://github.com/user-attachments/assets/6bb2dad0-5b37-4ad5-af20-a659c996e9db">
