### ISSUE TITLE
6. Селекторы

### ISSUE THREAD

**Issue by AAKholod** [CTEI1AH/SBZalesky_Uipath_SecHash#6]
Я бы не привязывалась к полному названию вкладки, лучше оставить "ACME System 1"

![image](https://github.com/user-attachments/assets/393961fc-2afe-4a25-b832-20b144aeeb3b)

**Comment by CTEI1AH** [comment]
<img width="355" alt="{58752584-762A-4FD1-AA50-953350CAFB38}" src="https://github.com/user-attachments/assets/3c939c26-4ab2-43ba-85e1-43e5f119c91a">
ок

**Comment by CTEI1AH** [comment]
Пробел тоже убрал
